import type { AnalyticsSnapshot, Campaign, ContentIdea, Post, Report, ScheduledPost, SocialAccount, Workspace } from "../types";
export const mapWorkspace = (r: any): Workspace => ({ id:r.id, brandName:r.name, industry:r.industry??"", targetAudience:r.target_audience??"", mainPlatforms:r.platforms??[], contentGoals:r.content_goals??[], toneOfVoice:r.brand_tone??"", planTier:r.plan_tier??"free" });
export const mapPost = (r:any): Post => ({ id:r.id,socialAccountId:r.social_account_id??undefined,title:r.title??"",platform:r.platform,contentType:r.content_type??"Text",datePosted:(r.posted_at??r.created_at??"").slice(0,10),likes:r.likes??0,comments:r.comments??0,shares:r.shares??0,saves:r.saves??0,reach:r.reach??0,impressions:r.impressions??0,campaignId:r.campaign_id??undefined,contentGoal:r.content_goal??"",postingTime:r.posted_at?.slice(11,16),isShort:r.is_short??undefined,retentionRate:r.retention_rate!=null?Number(r.retention_rate):undefined });
export const mapScheduledPost=(r:any):ScheduledPost=>({id:r.id,title:r.title??"",platform:r.platform,contentType:r.content_type??"Text",scheduledDate:(r.scheduled_at??r.created_at??"").slice(0,10),status:(r.status??"Draft").replace(/(^|_)([a-z])/g,(_:string,_p:string,c:string)=>` ${c.toUpperCase()}`).trim(),campaignId:r.campaign_id??undefined,contentGoal:r.content_goal??"",notes:r.caption??""} as ScheduledPost);
export const mapIdea=(r:any):ContentIdea=>({id:r.id,title:r.title,platform:r.platform??"Instagram",format:r.format??"Text",goal:r.goal??"",priority:r.priority??"Medium",status:r.status??"Backlog",notes:r.notes??""});
export const mapCampaign=(r:any):Campaign=>({id:r.id,name:r.name,goal:r.goal??"",startDate:r.start_date??"",endDate:r.end_date??"",platforms:r.platforms??[],attachedPostIds:[],status:(r.status??"planned").replace(/^./,(c:string)=>c.toUpperCase())});
export const mapReport=(r:any):Report=>({id:r.id,type:(r.report_type??"Weekly").replace(/^./,(c:string)=>c.toUpperCase()),title:r.title??"Performance snapshot",dateRange:[r.date_range_start,r.date_range_end].filter(Boolean).join(" to ")||"Current workspace",dateRangeStart:r.date_range_start??undefined,dateRangeEnd:r.date_range_end??undefined,totalPosts:r.total_posts??0,totalReach:r.total_reach??0,totalEngagement:r.total_engagement??0,averageEngagementRate:Number(r.average_engagement_rate??0),topPostId:r.top_post_id??undefined,topPost:r.top_post?.title??"No top post recorded",recommendations:r.recommendations??[]});
export const mapAccount=(r:any):SocialAccount=>({id:r.id,workspaceId:r.workspace_id,platform:r.platform,accountName:r.account_name??"",accountHandle:r.account_handle??"",connectionStatus:r.connection_status??"connected",importMode:r.import_mode??"from_today",lastSyncedAt:r.last_synced_at??undefined,scopes:r.scopes??[],providerMeta:r.provider_meta??undefined});
export const mapSnapshot=(r:any):AnalyticsSnapshot=>({id:r.id,workspaceId:r.workspace_id,socialAccountId:r.social_account_id,platform:r.platform,snapshotDate:r.snapshot_date,followers:r.followers??0,totalPosts:r.total_posts??0,totalReach:r.total_reach??0,totalImpressions:r.total_impressions??0,totalEngagement:r.total_engagement??0,averageEngagementRate:Number(r.average_engagement_rate??0)});
