import { useMemo, useState } from "react";
import { CalendarPlus, Clock3, CalendarX2 } from "lucide-react";
import type { AppDataProps } from "../App"; import { contentTypes, platforms } from "../data/options";
import type { ContentType, ScheduleStatus, ScheduledPost, SocialPlatform } from "../types";
import { addDays, toDateKey } from "../utils/dates";
import Badge from "./Badge"; import Modal from "./Modal";
import EmptyState from "./EmptyState"; import PageHeader from "./PageHeader";
const statuses: ScheduleStatus[] = ["Idea", "Draft", "In Review", "Approved", "Scheduled", "Published", "Failed"];
const createBlank = () => ({ title: "", platform: "Instagram" as SocialPlatform, contentType: "Reel" as ContentType, scheduledDate: toDateKey(addDays(new Date(), 1)), status: "Scheduled" as ScheduleStatus, campaignId: "", contentGoal: "Build trust", notes: "" });
export default function Calendar({ scheduledPosts, setScheduledPosts, campaigns }: AppDataProps) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState(createBlank); const [platform, setPlatform] = useState("All"); const [status, setStatus] = useState("All"); const [view, setView] = useState<"Week" | "Month">("Month");
  const items = useMemo(() => { const today = new Date(); const start = toDateKey(today); const end = view === "Week" ? toDateKey(addDays(today, 6)) : toDateKey(new Date(today.getFullYear(), today.getMonth() + 1, 0)); return scheduledPosts.filter((post) => post.scheduledDate >= start && post.scheduledDate <= end).filter((post) => platform === "All" || post.platform === platform).filter((post) => status === "All" || post.status === status).sort((a, b) => a.scheduledDate.localeCompare(b.scheduledDate)); }, [scheduledPosts, platform, status, view]);
  const add = () => { if (!form.title.trim()) return; setScheduledPosts((current) => [...current, { ...form, id: crypto.randomUUID(), campaignId: form.campaignId || undefined }]); setForm(createBlank()); setOpen(false); };
  const updateStatus = (id: string, next: ScheduleStatus) => setScheduledPosts((current) => current.map((post) => post.id === id ? { ...post, status: next } : post));
  return <div className="space-y-7"><PageHeader eyebrow="Publishing workflow" title="Content calendar" description="Move every post from early idea to published content without losing track of the next action." action={<button className="button-primary" onClick={() => setOpen(true)}><CalendarPlus size={16} /> Schedule post</button>} />
    <div className="flex flex-col gap-3 sm:flex-row"><div className="flex rounded-xl bg-white p-1 shadow-card">{(["Week", "Month"] as const).map((item) => <button key={item} onClick={() => setView(item)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${view === item ? "bg-slate-900 text-white" : "text-slate-400"}`}>{item}</button>)}</div><select aria-label="Filter calendar by platform" className="input sm:w-44" value={platform} onChange={(e) => setPlatform(e.target.value)}><option>All</option>{platforms.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter calendar by status" className="input sm:w-44" value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div>
    {items.length ? <div className={`grid gap-4 ${view === "Week" ? "md:grid-cols-2" : "md:grid-cols-2 xl:grid-cols-3"}`}>{items.map((post) => <article key={post.id} className="card card-hover p-5"><div className="flex items-center justify-between"><Badge>{post.status}</Badge><span className="text-xs font-semibold text-slate-400">{post.platform}</span></div><h3 className="mt-5 text-sm font-semibold leading-6 text-slate-800">{post.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-400">{post.notes || post.contentGoal}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4 text-xs text-slate-400"><span className="flex items-center gap-1.5"><Clock3 size={14} />{post.scheduledDate}</span><span>{post.contentType}</span></div><select aria-label={`Update status for ${post.title}`} className="input mt-4 text-xs" value={post.status} onChange={(e) => updateStatus(post.id, e.target.value as ScheduleStatus)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></article>)}</div> : <EmptyState icon={CalendarX2} title="Nothing in this view yet" description="Adjust your filters or add a scheduled post to keep the publishing pipeline visible." action={<button className="button-primary" onClick={() => setOpen(true)}><CalendarPlus size={16} /> Schedule post</button>} />}
    {open && <Modal title="Schedule a post" onClose={() => setOpen(false)}><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Post title</span><input className="input" placeholder="e.g. Three reasons families choose our school" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><span className="helper">Use a working title your team can identify quickly.</span></label><label><span className="label">Platform</span><select className="input" value={form.platform} onChange={(e) => setForm({ ...form, platform: e.target.value as SocialPlatform })}>{platforms.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="label">Format</span><select className="input" value={form.contentType} onChange={(e) => setForm({ ...form, contentType: e.target.value as ContentType })}>{contentTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="label">Publish date</span><input type="date" className="input" value={form.scheduledDate} onChange={(e) => setForm({ ...form, scheduledDate: e.target.value })} /></label><label><span className="label">Workflow status</span><select className="input" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as ScheduleStatus })}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label className="sm:col-span-2"><span className="label">Campaign</span><select className="input" value={form.campaignId} onChange={(e) => setForm({ ...form, campaignId: e.target.value })}><option value="">No campaign</option>{campaigns.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="sm:col-span-2"><span className="label">Content goal</span><input className="input" placeholder="e.g. Build trust or increase inquiries" value={form.contentGoal} onChange={(e) => setForm({ ...form, contentGoal: e.target.value })} /></label><label className="sm:col-span-2"><span className="label">Notes</span><textarea className="input min-h-20" placeholder="Add the hook, CTA, owner, or review notes." value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><button className="button-primary sm:col-span-2" onClick={add}>Add to calendar</button></div></Modal>}
  </div>;
}
