import { useState } from "react";
import { ArrowUpRight, Flag, Plus, Target } from "lucide-react";
import type { AppDataProps } from "../App"; import { platforms } from "../data/options";
import type { CampaignStatus, SocialPlatform } from "../types";
import { engagementRate, engagementTotal, formatNumber } from "../utils/analytics"; import Badge from "./Badge"; import Modal from "./Modal";
import { addDays, toDateKey } from "../utils/dates";
import { platformLabel } from "../utils/channels";
import EmptyState from "./EmptyState"; import PageHeader from "./PageHeader";
import SocialPlatformIcon from "./SocialPlatformIcon";
const createBlank = () => ({ name: "", goal: "", startDate: toDateKey(new Date()), endDate: toDateKey(addDays(new Date(), 30)), platforms: ["Instagram"] as SocialPlatform[], status: "Planning" as CampaignStatus });
export default function Campaigns({ campaigns, setCampaigns, posts }: AppDataProps) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState(createBlank);
  const add = () => { if (!form.name.trim() || !form.platforms.length) return; setCampaigns((current) => [...current, { ...form, id: crypto.randomUUID(), attachedPostIds: [] }]); setForm(createBlank()); setOpen(false); };
  const togglePlatform = (platform: SocialPlatform) => setForm({ ...form, platforms: form.platforms.includes(platform) ? form.platforms.filter((item) => item !== platform) : [...form.platforms, platform] });
  return <div className="space-y-7"><PageHeader eyebrow="Organize your work" title="Campaigns" description="Group posts around a clear objective, then compare reach and engagement in context." action={<button className="button-primary" onClick={() => setOpen(true)}><Plus size={16} /> New campaign</button>} />
    <div className="grid gap-4 xl:grid-cols-3">{campaigns.length ? campaigns.map((campaign) => { const campaignPosts = posts.filter((post) => post.campaignId === campaign.id || campaign.attachedPostIds.includes(post.id)); const totalEngagement = campaignPosts.reduce((sum, post) => sum + engagementTotal(post), 0); const totalReach = campaignPosts.reduce((sum, post) => sum + post.reach, 0); return <article key={campaign.id} className="card card-hover flex flex-col p-5 sm:p-6"><div className="flex items-center justify-between"><span className="rounded-2xl bg-slate-50 p-2.5 text-slate-500"><Flag size={17} /></span><Badge>{campaign.status}</Badge></div><h3 className="mt-5 font-semibold tracking-tight text-slate-900">{campaign.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-400">{campaign.goal}</p><p className="mt-4 text-xs text-slate-400">{campaign.startDate} to {campaign.endDate}</p><div className="mt-3 flex flex-wrap gap-1.5">{campaign.platforms.map((platform) => <span key={platform} className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500"><SocialPlatformIcon platform={platform} size="sm" />{platformLabel(platform)}</span>)}</div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-slate-100 pt-4"><div><p className="text-lg font-semibold tracking-tight">{campaignPosts.length}</p><p className="text-[10px] uppercase tracking-wider text-slate-400">Posts</p></div><div><p className="text-lg font-semibold tracking-tight">{formatNumber(totalReach)}</p><p className="text-[10px] uppercase tracking-wider text-slate-400">Reach</p></div><div><p className="text-lg font-semibold tracking-tight">{campaignPosts.length ? (campaignPosts.reduce((sum, post) => sum + engagementRate(post), 0) / campaignPosts.length).toFixed(1) : "0.0"}%</p><p className="text-[10px] uppercase tracking-wider text-slate-400">{formatNumber(totalEngagement)} eng.</p></div></div><button className="mt-5 flex items-center gap-1 text-xs font-semibold text-slate-500 transition hover:text-slate-900">Review campaign <ArrowUpRight size={13} /></button></article>; }) : <EmptyState icon={Target} title="Create your first campaign" description="Campaigns help teams, schools, organizations, and creators group posts around a measurable outcome." className="xl:col-span-3" action={<button className="button-primary" onClick={() => setOpen(true)}><Plus size={16} /> New campaign</button>} />}</div>
    {open && <Modal title="Create campaign" onClose={() => setOpen(false)}><div className="space-y-4"><label><span className="label">Campaign name</span><input className="input" placeholder="e.g. Back-to-school enrollment" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><span className="helper">Choose a name your team will recognize quickly.</span></label><label><span className="label">Primary goal</span><textarea className="input min-h-20" placeholder="What should this campaign achieve?" value={form.goal} onChange={(e) => setForm({ ...form, goal: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Start date</span><input type="date" className="input" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /></label><label><span className="label">End date</span><input type="date" className="input" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></label></div><div><span className="label">Platforms</span><div className="flex flex-wrap gap-2">{platforms.map((platform) => <button key={platform} type="button" onClick={() => togglePlatform(platform)} className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-xs font-semibold transition ${form.platforms.includes(platform) ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-500 hover:bg-slate-200"}`}><SocialPlatformIcon platform={platform} size="sm" />{platformLabel(platform)}</button>)}</div><span className="helper">Select every channel included in this campaign.</span></div><label><span className="label">Status</span><select className="input" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as CampaignStatus })}><option>Planning</option><option>Active</option><option>Completed</option><option>Paused</option></select></label><button disabled={!form.name.trim() || !form.platforms.length} className="button-primary w-full disabled:cursor-not-allowed disabled:opacity-40" onClick={add}>Create campaign</button></div></Modal>}
  </div>;
}
