import { ArrowUpRight, CalendarCheck, Eye, Heart, Layers3, Lightbulb, Radio, Send, Sparkles, TrendingUp } from "lucide-react";
import type { AppDataProps } from "../App";
import { engagementTotal, formatNumber } from "../utils/analytics";
import { generateRecommendations, getAverageEngagementRate, getBestContentType, getBestPlatform, getBestPostingDay, getScheduledPostsThisWeek, getTopPosts, getTotalEngagement } from "../utils/recommendations";
import StatCard from "./StatCard";
import PageHeader from "./PageHeader";
import EmptyState from "./EmptyState";

export default function Dashboard({ posts, scheduledPosts, ideas, workspace, onNavigate }: AppDataProps) {
  const topPosts = getTopPosts(posts); const recommendations = generateRecommendations(posts, scheduledPosts, ideas);
  const recentPosts = [...posts].sort((a, b) => a.datePosted.localeCompare(b.datePosted)).slice(-7); const maxEngagement = Math.max(...recentPosts.map(engagementTotal), 1); const engagementTrend = recentPosts.map((post) => ({ label: post.datePosted.slice(5), value: Math.max((engagementTotal(post) / maxEngagement) * 100, 8) }));
  const platformTotals = [...new Set(posts.map((post) => post.platform))].map((platform) => ({ platform, rate: getAverageEngagementRate(posts.filter((post) => post.platform === platform)) })).sort((a, b) => b.rate - a.rate);
  return <div className="space-y-7">
    <PageHeader eyebrow="Workspace overview" title={`Good morning, ${workspace.brandName}`} description="A clear view of what is working, what is scheduled, and where to focus next." action={<button className="button-secondary" onClick={() => onNavigate?.("Calendar")}><CalendarCheck size={16} /> View calendar</button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard label="Total posts" value={String(posts.length)} helper="Published content" icon={Send} /><StatCard label="Total reach" value={formatNumber(posts.reduce((sum, post) => sum + post.reach, 0))} helper="Across tracked channels" icon={Eye} /><StatCard label="Total engagement" value={formatNumber(getTotalEngagement(posts))} helper="Across tracked posts" icon={Heart} /><StatCard label="Average rate" value={`${getAverageEngagementRate(posts).toFixed(1)}%`} helper="Engagement by reach" icon={TrendingUp} />
      <StatCard label="Best platform" value={getBestPlatform(posts)} helper="Highest average rate" icon={Radio} /><StatCard label="Best content type" value={getBestContentType(posts)} helper="Based on engagement" icon={Layers3} /><StatCard label="Best posting day" value={getBestPostingDay(posts)} helper="Strongest average result" icon={TrendingUp} /><StatCard label="Scheduled this week" value={String(getScheduledPostsThisWeek(scheduledPosts).length)} helper="Keep the queue moving" icon={CalendarCheck} />
    </div>
    <div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]">
      <section className="card p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="section-title">Engagement trend</h2><p className="section-copy">Recent content performance across your active channels.</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-emerald-700">Tracked signal</span></div><div className="mt-8 flex h-48 items-end gap-2 sm:gap-3">{engagementTrend.map((item) => <div key={item.label} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="relative flex flex-1 items-end rounded-lg bg-slate-50"><div className="w-full rounded-lg bg-slate-900 transition hover:bg-slate-700" style={{ height: `${item.value}%` }} /></div><span className="text-center text-[9px] text-slate-400 sm:text-[10px]">{item.label}</span></div>)}</div></section>
      <section className="card p-5 sm:p-6"><h2 className="section-title">Platform health</h2><p className="section-copy">Average engagement rate by channel.</p><div className="mt-6 space-y-4">{platformTotals.map(({ platform, rate }) => <div key={platform}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-slate-600">{platform}</span><span className="text-slate-400">{rate.toFixed(1)}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-900" style={{ width: `${Math.min(rate * 8, 100)}%` }} /></div></div>)}</div></section>
    </div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]">
      {topPosts.length ? <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 sm:px-6"><div><h2 className="section-title">Top-performing posts</h2><p className="section-copy">Your strongest content by total engagement.</p></div><button onClick={() => onNavigate?.("Analytics")} className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-50 hover:text-slate-800"><ArrowUpRight size={17} /></button></div>{topPosts.map((post) => <div key={post.id} className="flex items-center gap-4 border-b border-slate-100 px-5 py-4 transition last:border-0 hover:bg-slate-50/70 sm:px-6"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-700">{post.title}</p><p className="mt-1 text-xs text-slate-400">{post.platform} / {post.contentType}</p></div><p className="text-sm font-semibold text-slate-900">{formatNumber(engagementTotal(post))}</p></div>)}</section> : <EmptyState icon={Lightbulb} title="No performance leaders yet" description="Track a published post to identify your strongest content." />}
      <section className="card p-5 sm:p-6"><div className="flex items-center gap-2"><Sparkles size={17} className="text-slate-500" /><h2 className="section-title">Smart recommendations</h2></div><p className="section-copy">Rule-based next steps from your current content data.</p><div className="mt-4 space-y-3">{recommendations.map((item) => <div key={item.id} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-3.5"><p className="text-sm font-semibold text-slate-700">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-400">{item.detail}</p></div>)}</div></section>
    </div>
  </div>;
}
