import { useState } from "react";
import { ArrowRight, Lightbulb, Plus, Sparkles } from "lucide-react";
import type { AppDataProps } from "../App"; import { contentTypes, platforms } from "../data/options";
import type { ContentIdea, ContentType, Priority, SocialPlatform } from "../types"; import Badge from "./Badge";
import { addDays, toDateKey } from "../utils/dates";
import { accountForPlatform, orderedPlatforms, platformLabel } from "../utils/channels";
import EmptyState from "./EmptyState"; import PageHeader from "./PageHeader";
const blank = { title: "", platform: "Instagram" as SocialPlatform, format: "Reel" as ContentType, goal: "Build trust", priority: "Medium" as Priority, status: "Backlog" as const, notes: "" };
export default function Ideas({ ideas, setIdeas, setScheduledPosts, socialAccounts, onNavigate }: AppDataProps) {
  const [show, setShow] = useState(false); const [topic, setTopic] = useState(""); const [form, setForm] = useState(blank); const [platformFilter, setPlatformFilter] = useState<"All" | SocialPlatform>("All");
  const channelOrder = orderedPlatforms(socialAccounts);
  const filteredIdeas = ideas.filter((idea) => platformFilter === "All" || idea.platform === platformFilter);
  const add = () => { if (!form.title.trim()) return; setIdeas((current) => [...current, { ...form, id: crypto.randomUUID() }]); setForm(blank); setShow(false); };
  const generate = () => { const subject = topic.trim() || "personal branding"; const school = subject.toLowerCase().includes("school"); const titles = school ? ["A day in the life of a student", "5 reasons parents choose this school", "Behind the scenes with teachers", "What makes our learning community different"] : [`3 mistakes to avoid with ${subject}`, `My simple ${subject} checklist`, `Behind the scenes: how I approach ${subject}`, `What no one tells you about ${subject}`]; setIdeas((current) => [...current, ...titles.map((title) => ({ ...blank, id: crypto.randomUUID(), title, notes: `Generated from topic: ${subject}` }))]); };
  const schedule = (idea: ContentIdea) => { setScheduledPosts((current) => [...current, { id: crypto.randomUUID(), title: idea.title, platform: idea.platform, contentType: idea.format, scheduledDate: toDateKey(addDays(new Date(), 1)), status: "Draft", contentGoal: idea.goal, notes: idea.notes }]); setIdeas((current) => current.map((item) => item.id === idea.id ? { ...item, status: "Scheduled" } : item)); onNavigate?.("Calendar"); };
  return <div className="space-y-7"><PageHeader eyebrow="Creative pipeline" title="Content ideas" description="Track ideas by channel, including plans created from the calendar." action={<button className="button-primary" onClick={() => setShow(!show)}><Plus size={16} /> New idea</button>} />
    <section className="card p-4"><div className="flex gap-2 overflow-x-auto"><button onClick={() => setPlatformFilter("All")} className={`shrink-0 rounded-xl px-3 py-2 text-sm font-semibold ${platformFilter === "All" ? "bg-slate-950 text-white" : "bg-slate-50 text-slate-500"}`}>All ideas</button>{channelOrder.map((item) => { const account = accountForPlatform(socialAccounts, item); return <button key={item} onClick={() => setPlatformFilter(item)} className={`shrink-0 rounded-xl border px-3 py-2 text-left text-sm ${platformFilter === item ? "border-slate-950 bg-slate-950 text-white" : account ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-slate-200 bg-white text-slate-500"}`}><span className="block font-semibold">{platformLabel(item)}</span><span className="block text-[11px] opacity-70">{ideas.filter((idea) => idea.platform === item).length} ideas</span></button>; })}</div></section>
    {show && <section className="card grid gap-4 p-5 lg:grid-cols-3"><label className="lg:col-span-2"><span className="label">Idea title</span><input className="input" placeholder="e.g. A day in the life of our volunteer team" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label><span className="label">Platform</span><select className="input" value={form.platform} onChange={(e) => setForm({ ...form, platform: e.target.value as SocialPlatform })}>{channelOrder.map((item) => <option key={item} value={item}>{platformLabel(item)}</option>)}</select></label><label><span className="label">Format</span><select className="input" value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value as ContentType })}>{contentTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="label">Goal</span><input className="input" placeholder="e.g. Build trust" value={form.goal} onChange={(e) => setForm({ ...form, goal: e.target.value })} /></label><label><span className="label">Priority</span><select className="input" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as Priority })}><option>High</option><option>Medium</option><option>Low</option></select></label><label className="lg:col-span-3"><span className="label">Notes</span><textarea className="input min-h-20" placeholder="Capture the hook, audience takeaway, or reference links." value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><button className="button-primary lg:col-span-3" onClick={add}>Save idea</button></section>}
    <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="grid gap-4 md:grid-cols-2">{filteredIdeas.length ? filteredIdeas.map((idea) => <article key={idea.id} className="card card-hover flex flex-col p-5"><div className="flex justify-between gap-3"><span className="rounded-xl bg-slate-50 p-2 text-slate-500"><Lightbulb size={16} /></span><div className="flex flex-wrap justify-end gap-2"><Badge>{idea.priority}</Badge><Badge>{idea.status}</Badge></div></div><h3 className="mt-5 text-sm font-semibold leading-6 text-slate-800">{idea.title}</h3><p className="mt-2 flex-1 text-xs leading-5 text-slate-400">{idea.notes}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><p className="text-xs font-medium text-slate-500">{platformLabel(idea.platform)} / {idea.format}</p>{idea.status !== "Scheduled" && <button onClick={() => schedule(idea)} className="flex items-center gap-1 text-xs font-semibold text-slate-700 transition hover:text-slate-400">Schedule <ArrowRight size={13} /></button>}</div></article>) : <EmptyState icon={Lightbulb} title="Your idea pipeline is ready" description="Capture a concept manually or create one from the calendar." className="md:col-span-2" />}</section><aside className="card h-fit overflow-hidden"><div className="bg-slate-900 p-5 text-white"><div className="flex items-center gap-2"><Sparkles size={17} /><h3 className="font-semibold">Idea generator</h3></div><p className="mt-2 text-sm leading-6 text-slate-300">Turn a broad topic into a small set of usable prompts.</p></div><div className="p-5"><input className="input" value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Try: school enrollment" /><button className="button-primary mt-3 w-full" onClick={generate}><Sparkles size={15} /> Generate ideas</button></div></aside></div>
  </div>;
}
