import { Download, FileText, Plus, Sparkles } from "lucide-react";
import type { AppDataProps } from "../App";
import { formatNumber } from "../utils/analytics";
import { generateRecommendations, getAverageEngagementRate, getTopPosts, getTotalEngagement } from "../utils/recommendations";
import Badge from "./Badge";
import PageHeader from "./PageHeader"; import EmptyState from "./EmptyState";
export default function Reports({ reports, setReports, posts, scheduledPosts, ideas }: AppDataProps) {
  const generate = () => { const recs = generateRecommendations(posts, scheduledPosts, ideas); const topPost = getTopPosts(posts, 1)[0]; const end = new Date(); const start = new Date(end); start.setDate(end.getDate() - 6); const dateRangeStart = start.toISOString().slice(0, 10); const dateRangeEnd = end.toISOString().slice(0, 10); setReports((current) => [{ id: crypto.randomUUID(), type: "Weekly", title: "Generated performance snapshot", dateRange: `${dateRangeStart} to ${dateRangeEnd}`, dateRangeStart, dateRangeEnd, totalPosts: posts.length, totalReach: posts.reduce((sum, post) => sum + post.reach, 0), totalEngagement: getTotalEngagement(posts), averageEngagementRate: getAverageEngagementRate(posts), topPostId: topPost?.id, topPost: topPost?.title ?? "No posts yet", recommendations: recs.slice(0, 3).map((item) => item.title) }, ...current]); };
  return <div className="space-y-7"><PageHeader eyebrow="Share the story" title="Reports" description="Turn your tracked content into clear performance summaries for teammates, clients, and stakeholders." action={<button className="button-primary" onClick={generate}><Plus size={16} /> Generate report</button>} />
    <section className="card overflow-hidden bg-slate-900 p-5 text-white shadow-lg sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-slate-300"><Sparkles size={15} /><p className="text-[10px] font-bold uppercase tracking-[0.18em]">Workspace report studio</p></div><h3 className="mt-3 text-xl font-semibold tracking-tight">Build a stakeholder-ready snapshot in one click.</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Reports summarize your tracked data and recommendations. PDF export is prepared as the next integration step.</p></div><button className="shrink-0 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-900 transition hover:bg-slate-100" onClick={generate}>Generate snapshot</button></div></section>
    <div className="grid gap-4 xl:grid-cols-2">{reports.length ? reports.map((report) => <article key={report.id} className="card card-hover p-5 sm:p-6"><div className="flex items-start justify-between"><span className="rounded-2xl bg-slate-50 p-2.5 text-slate-500"><FileText size={17} /></span><Badge>{report.type}</Badge></div><h3 className="mt-5 font-semibold tracking-tight text-slate-900">{report.title}</h3><p className="mt-1 text-xs text-slate-400">{report.dateRange}</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Posts", String(report.totalPosts)], ["Reach", formatNumber(report.totalReach)], ["Engagements", formatNumber(report.totalEngagement)], ["Avg. rate", `${report.averageEngagementRate.toFixed(1)}%`]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="font-semibold tracking-tight text-slate-900">{value}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">{label}</p></div>)}</div><div className="mt-5 rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Top post</p><p className="mt-2 text-sm font-semibold text-slate-700">{report.topPost}</p></div><div className="mt-5"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Recommended next steps</p><ul className="mt-3 space-y-2">{report.recommendations.map((item, index) => <li key={`${item}-${index}`} className="flex gap-2 text-xs leading-5 text-slate-500"><span className="text-slate-300">0{index + 1}</span>{item}</li>)}</ul></div><button type="button" className="button-secondary mt-5"><Download size={15} /> Export PDF</button>{/* Connect PDF generation or backend export here later. */}</article>) : <EmptyState icon={FileText} title="No reports generated yet" description="Create your first snapshot to summarize performance and recommendations." className="xl:col-span-2" action={<button className="button-primary" onClick={generate}>Generate report</button>} />}</div>
  </div>;
}
